import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../constants/app_constants.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'location': 'Location',
      'search': 'Search...',
      'results': 'Results',
      'select_category': 'Select Category',
      'no_products_found': 'No products found',
      'choose_location': 'Choose location',
      'select_location': 'Select location',
      'enter_city_name': 'Enter the city name',
      'search_button': 'Search',
      'recent': 'Recent',
      'error_min_letters': 'Type at least 3 letters',
      'error_fetching_cities': 'Error fetching cities',
      'filters': 'Filters',
      'pump': 'PUMP',
      'others': 'OTHERS',
      'models': 'Models',
      'frequency': 'Frequency',
      'flow': 'Flow',
      'manometric_head': 'Manometric Head',
      'power': 'Power',
      'rotation': 'Rotation',
      'max_pressure': 'Max Pressure',
      'max_flow': 'Max Flow',
      'technical_sheet': 'Technical Sheet',
      'features': 'Features',
      'specifications': 'Specifications',
      'options': 'Options',
      'applications': 'Applications',
      'technical_comparison': 'Technical Comparison',
      'pick_one': 'Pick one',
      'Ficha Técnica': 'Technical Sheet',
      'Características': 'Features',
      'Especificações': 'Specifications',
      'Opções': 'Options',
      'Aplicações': 'Applications',
      'Documentos': 'Documents',
      'Nenhum documento disponível': 'No documents available',
      'all': 'ALL',
      'ALL': 'All',
      'system_type': 'System Type',
      'well_diameter': 'Well Diameter',
      'cable_length': 'Cable Length',
      'activation_type': 'Activation Type',
      'pressure_switch': 'Pressure Switch',
      'frequency_inverter': 'Frequency Inverter',
      'pumps_quantity': 'Pumps Quantity',
      'Micropump': 'Micropump',
      'Submersible': 'Submersible',
      'Surface': 'Surface',
      'DIRECT CURRENT': 'Direct Current',
      'ALTERNATING CURRENT': 'Alternating Current',
      'ecaros-solar-system': 'Écaros Solar System',
      'ecaros-solar-system-1': 'Écaros Solar System',
      'sistema-solar-ecaros-1': 'Écaros Solar System',
      'welcome': 'Welcome',
      'login_desc': 'Log in to save your preferences or continue as a guest.',
      'enter_google': 'Sign in with Google',
      'continue_guest': 'Continue as Guest',
      'login_error': 'Error logging in with Google',
      'want_login': 'Do you want to log in?',
      'my_account': 'My Account',
      'guest_modal_desc':
          'Log in with Google to save your preferences and access exclusive features.',
      'user': 'User',
      'connect_error': 'Error connecting with Google',
      'back_login': 'Back to Login Screen',
      'logout': 'Logout',
      'favorites': 'Favorites',
      'login_to_favorite': 'Log in to save to favorites',
      'login_to_download': 'Log in to download files',
      'exclusive_feature': 'Exclusive Feature',
      'history': 'History',
      'recent_products': 'Recent Products',
      'no_recent_products': 'No products viewed recently',
      'clear': 'Clear',
      'share_text': 'Check out this product: {name} - Model: {model}.',
      'loading_product': 'Loading product...',
      'product_not_found': 'Product not found',
      'dark_mode': 'Dark Mode',
      'calculators': 'Calculators',
      'unit_converter': 'Converter',
      'hydraulic_calc': 'Hydraulic',
      'electric_calc': 'Electric',
      'pressure': 'Pressure',
      'length': 'Length',
      'diameter': 'Diameter',
      'material': 'Material',
      'pvc': 'PVC',
      'iron': 'Iron',
      'head_loss': 'Head Loss',
      'voltage_drop': 'Voltage Drop',
      'current': 'Current',
      'voltage': 'Voltage',
      'cable_section': 'Cable Section',
      'calculate': 'Calculate',
      'result': 'Result',
      'input_value': 'Input value',
      'try_again': 'Try Again',
      'no_internet': 'No internet connection',
      'offline_mode': 'You are in offline mode',
      'from': 'From',
      'to': 'To',
      'tap_to_copy': 'Tap to copy',
      'comparison_base': 'Base',
      'comparison_current': 'Current',
      'pump_selector': 'Pump Selector',
      'required_field': 'Required field',
      'mandatory': 'Mandatory',
      'update_available': 'Update Available',
      'update_desc':
          'A new version of the app is available. Update now to access new features.',
      'update_now': 'Update Now',
      'later': 'Later',
      'buy': 'Buy',
      'representatives': 'Representatives',
      'no_representatives_found': 'No representatives found\nnear {city}',
      'error_downloading': 'Error downloading file',
      'variation': 'VARIATION',
      'offline_catalog_updated':
          'Offline catalog updated! ({count} categories processed)',
      'error_starting_download': 'Error starting download',
      'starting_download': 'Starting Download',
      'download_background_info':
          'The download will continue in the background. Track progress via the notification bar.',
      'background_downloads': 'Background Downloads',
      'downloading_offline_catalog': 'Downloading Offline Catalog',
      'processing_category_progress':
          'Processing category {current} of {total} ({progress}%)',
      'download_completed': 'Download Completed',
      'offline_catalog_success':
          'The offline catalog has been successfully updated.',
      'download_error': 'Download Error',
      'error_downloading_catalog':
          'An error occurred while downloading the catalog.',
      'syncing_data': 'Syncing Data',
      'sync_completed': 'Sync Completed',
      'data_updated_server': 'Data has been updated with the server.',
      'operation_error': 'Operation Error',
      'error_processing_data': 'An error occurred while processing data.',
    },
    'pt': {
      'location': 'Localização',
      'search': 'Buscar...',
      'results': 'Resultados',
      'select_category': 'Selecione a Categoria',
      'no_products_found': 'Nenhum produto encontrado',
      'choose_location': 'Escolher localização',
      'select_location': 'Selecione a localização',
      'enter_city_name': 'Digite o nome da cidade',
      'search_button': 'Buscar',
      'recent': 'Recentes',
      'error_min_letters': 'Digite pelo menos 3 letras',
      'error_fetching_cities': 'Erro ao buscar cidades',
      'filters': 'Filtros',
      'pump': 'BOMBA',
      'others': 'OUTROS',
      'models': 'Modelos',
      'frequency': 'Frequência',
      'flow': 'Vazão',
      'manometric_head': 'Altura Manométrica',
      'power': 'Potência',
      'rotation': 'Rotação',
      'max_pressure': 'Pressão Máx.',
      'max_flow': 'Vazão Máx.',
      'technical_sheet': 'Ficha Técnica',
      'features': 'Características',
      'specifications': 'Especificações',
      'options': 'Opções',
      'applications': 'Aplicações',
      'technical_comparison': 'Comparativo Técnico',
      'pick_one': 'Selecione um',
      'Ficha Técnica': 'Ficha Técnica',
      'Características': 'Características',
      'Especificações': 'Especificações',
      'Opções': 'Opções',
      'Aplicações': 'Aplicações',
      'Documentos': 'Documentos',
      'Nenhum documento disponível': 'Nenhum documento disponível',
      'all': 'TODOS',
      'ALL': 'TODOS',
      'system_type': 'Tipo de Sistema',
      'well_diameter': 'Diâmetro do Poço',
      'cable_length': 'Comprimento do Cabo',
      'activation_type': 'Tipo de Acionamento',
      'pressure_switch': 'Pressostato',
      'frequency_inverter': 'Inversor de Frequência',
      'pumps_quantity': 'Quantidade de Bombas',
      'Micropump': 'Microbomba',
      'Submersible': 'Submersível',
      'Surface': 'Superfície',
      'DIRECT CURRENT': 'Corrente Contínua',
      'ALTERNATING CURRENT': 'Corrente Alternada',
      'ecaros-solar-system': 'Sistema Solar Écaros',
      'ecaros-solar-system-1': 'Sistema Solar Écaros',
      'sistema-solar-ecaros-1': 'Sistema Solar Écaros',
      'welcome': 'Bem-vindo',
      'login_desc':
          'Faça login para salvar suas preferências ou continue como visitante.',
      'enter_google': 'Entrar com Google',
      'continue_guest': 'Continuar como Visitante',
      'login_error': 'Erro ao realizar login com Google',
      'want_login': 'Deseja fazer login?',
      'my_account': 'Minha Conta',
      'guest_modal_desc':
          'Faça login com Google para salvar suas preferências e acessar recursos exclusivos.',
      'user': 'Usuário',
      'connect_error': 'Erro ao conectar com Google',
      'back_login': 'Voltar para Tela de Login',
      'logout': 'Sair da Conta',
      'favorites': 'Favoritos',
      'login_to_favorite': 'Faça login para salvar nos favoritos',
      'login_to_download': 'Faça login para baixar arquivos',
      'exclusive_feature': 'Recurso Exclusivo',
      'history': 'Histórico',
      'recent_products': 'Produtos Recentes',
      'no_recent_products': 'Nenhum produto visto recentemente',
      'clear': 'Limpar',
      'share_text': 'Confira este produto: {name} - Modelo: {model}.',
      'loading_product': 'Carregando produto...',
      'product_not_found': 'Produto não encontrado',
      'dark_mode': 'Modo Escuro',
      'calculators': 'Calculadoras',
      'unit_converter': 'Conversor',
      'hydraulic_calc': 'Hidráulica',
      'electric_calc': 'Elétrica',
      'pressure': 'Pressão',
      'length': 'Comprimento',
      'diameter': 'Diâmetro',
      'material': 'Material',
      'pvc': 'PVC',
      'iron': 'Ferro Galvanizado',
      'head_loss': 'Perda de Carga',
      'voltage_drop': 'Queda de Tensão',
      'current': 'Corrente',
      'voltage': 'Tensão',
      'cable_section': 'Seção do Cabo',
      'calculate': 'Calcular',
      'result': 'Resultado',
      'input_value': 'Digite o valor',
      'try_again': 'Tentar Novamente',
      'no_internet': 'Sem conexão com a internet',
      'offline_mode': 'Você está em modo offline',
      'from': 'De',
      'to': 'Para',
      'tap_to_copy': 'Toque para copiar',
      'comparison_base': 'Base',
      'comparison_current': 'Atual',
      'pump_selector': 'Seletor de Bombas',
      'required_field': 'Campo obrigatório',
      'mandatory': 'Obrigatório',
      'update_available': 'Atualização Disponível',
      'update_desc':
          'Uma nova versão do aplicativo está disponível. Atualize agora para acessar novos recursos.',
      'update_now': 'Atualizar Agora',
      'later': 'Depois',
      'buy': 'Comprar',
      'representatives': 'Representantes',
      'no_representatives_found':
          'Nenhum representante encontrado\npróximo a {city}',
      'error_downloading': 'Erro ao baixar arquivo',
      'variation': 'VARIAÇÃO',
      'offline_catalog_updated':
          'Catálogo offline atualizado! ({count} categorias processadas)',
      'error_starting_download': 'Erro ao iniciar download',
      'starting_download': 'Iniciando Download',
      'download_background_info':
          'O download continuará em segundo plano. Acompanhe o progresso pela barra de notificações.',
      'background_downloads': 'Downloads em Background',
      'downloading_offline_catalog': 'Baixando Catálogo Offline',
      'processing_category_progress':
          'Processando categoria {current} de {total} ({progress}%)',
      'download_completed': 'Download Concluído',
      'offline_catalog_success':
          'O catálogo offline foi atualizado com sucesso.',
      'download_error': 'Erro no Download',
      'error_downloading_catalog': 'Ocorreu um erro ao baixar o catálogo.',
      'syncing_data': 'Sincronizando Dados',
      'sync_completed': 'Sincronização Concluída',
      'data_updated_server': 'Os dados foram atualizados com o servidor.',
      'operation_error': 'Erro na Operação',
      'error_processing_data': 'Ocorreu um erro ao processar os dados.',
    },
    'es': {
      'location': 'Ubicación',
      'search': 'Buscar...',
      'results': 'Resultados',
      'select_category': 'Seleccionar Categoría',
      'no_products_found': 'No se encontraron productos',
      'choose_location': 'Elegir ubicación',
      'select_location': 'Seleccionar ubicación',
      'enter_city_name': 'Ingrese el nombre de la ciudad',
      'search_button': 'Buscar',
      'recent': 'Recientes',
      'error_min_letters': 'Escriba al menos 3 letras',
      'error_fetching_cities': 'Error al buscar ciudades',
      'filters': 'Filtros',
      'pump': 'BOMBA',
      'others': 'OTROS',
      'models': 'Modelos',
      'frequency': 'Frecuencia',
      'flow': 'Caudal',
      'manometric_head': 'Altura Manométrica',
      'power': 'Potencia',
      'rotation': 'Rotación',
      'max_pressure': 'Presión Máx.',
      'max_flow': 'Caudal Máx.',
      'technical_sheet': 'Ficha Técnica',
      'features': 'Características',
      'specifications': 'Especificaciones',
      'options': 'Opciones',
      'applications': 'Aplicaciones',
      'technical_comparison': 'Comparación Técnica',
      'pick_one': 'Seleccionar uno',
      'Ficha Técnica': 'Ficha Técnica',
      'Características': 'Características',
      'Especificações': 'Especificaciones',
      'Opções': 'Opciones',
      'Aplicações': 'Aplicaciones',
      'Documentos': 'Documentos',
      'Nenhum documento disponible': 'No hay documentos disponibles',
      'all': 'TODOS',
      'ALL': 'TODOS',
      'system_type': 'Tipo de Sistema',
      'well_diameter': 'Diámetro del Pozo',
      'cable_length': 'Longitud del Cable',
      'activation_type': 'Tipo de Activación',
      'pressure_switch': 'Presostato',
      'frequency_inverter': 'Variador de Frecuencia',
      'pumps_quantity': 'Cantidad de Bombas',
      'Micropump': 'Microbomba',
      'Submersible': 'Sumergible',
      'Surface': 'Superficie',
      'DIRECT CURRENT': 'Corriente Continua',
      'ALTERNATING CURRENT': 'Corriente Alterna',
      'ecaros-solar-system': 'Sistema Solar Écaros',
      'ecaros-solar-system-1': 'Sistema Solar Écaros',
      'sistema-solar-ecaros-1': 'Sistema Solar Écaros',
      'welcome': 'Bienvenido',
      'login_desc':
          'Inicia sesión para guardar tus preferencias o continúa como invitado.',
      'enter_google': 'Entrar con Google',
      'continue_guest': 'Continuar como Invitado',
      'login_error': 'Error al iniciar sesión con Google',
      'want_login': '¿Deseas iniciar sesión?',
      'my_account': 'Mi Cuenta',
      'guest_modal_desc':
          'Inicia sesión con Google para guardar tus preferencias y acceder a funciones exclusivas.',
      'user': 'Usuario',
      'connect_error': 'Error al conectar con Google',
      'back_login': 'Volver a inicio de sesión',
      'logout': 'Cerrar sesión',
      'favorites': 'Favoritos',
      'login_to_favorite': 'Inicia sesión para guardar en favoritos',
      'login_to_download': 'Inicia sesión para descargar archivos',
      'exclusive_feature': 'Función Exclusiva',
      'history': 'Historial',
      'recent_products': 'Productos Recientes',
      'no_recent_products': 'No hay productos vistos recientemente',
      'clear': 'Limpiar',
      'share_text': 'Mira este producto: {name} - Modelo: {model}.',
      'loading_product': 'Cargando producto...',
      'product_not_found': 'Producto no encontrado',
      'dark_mode': 'Modo Oscuro',
      'calculators': 'Calculadoras',
      'unit_converter': 'Convertidor',
      'hydraulic_calc': 'Hidráulica',
      'electric_calc': 'Eléctrica',
      'pressure': 'Presión',
      'length': 'Longitud',
      'diameter': 'Diámetro',
      'material': 'Material',
      'pvc': 'PVC',
      'iron': 'Hierro Galvanizado',
      'head_loss': 'Pérdida de Carga',
      'voltage_drop': 'Caída de Tensión',
      'current': 'Corriente',
      'voltage': 'Tensión',
      'cable_section': 'Sección del Cable',
      'calculate': 'Calcular',
      'result': 'Resultado',
      'input_value': 'Ingrese valor',
      'try_again': 'Intentar de nuevo',
      'no_internet': 'Sin conexión a internet',
      'offline_mode': 'Estás en modo offline',
      'from': 'De',
      'to': 'Para',
      'tap_to_copy': 'Toque para copiar',
      'comparison_base': 'Base',
      'comparison_current': 'Actual',
      'pump_selector': 'Selector de Bombas',
      'required_field': 'Campo obligatorio',
      'mandatory': 'Obligatorio',
      'update_available': 'Actualización Disponible',
      'update_desc':
          'Hay una nueva versión de la aplicación disponible. Actualice ahora para acceder a nuevas funciones.',
      'update_now': 'Actualizar Ahora',
      'later': 'Más tarde',
      'buy': 'Comprar',
      'representatives': 'Representantes',
      'no_representatives_found':
          'No se encontraron representantes\ncerca de {city}',
      'error_downloading': 'Error al descargar archivo',
      'variation': 'VARIACIÓN',
      'offline_catalog_updated':
          '¡Catálogo offline actualizado! ({count} categorías procesadas)',
      'error_starting_download': 'Error al iniciar la descarga',
      'starting_download': 'Iniciando descarga',
      'download_background_info':
          'La descarga continuará en segundo plano. Siga el progreso a través de la barra de notificaciones.',
      'background_downloads': 'Descargas en segundo plano',
      'downloading_offline_catalog': 'Descargando catálogo offline',
      'processing_category_progress':
          'Procesando categoría {current} de {total} ({progress}%)',
      'download_completed': 'Descarga completa',
      'offline_catalog_success':
          'El catálogo offline se ha actualizado correctamente.',
      'download_error': 'Error de descarga',
      'error_downloading_catalog': 'Ocurrió un error al descargar el catálogo.',
      'syncing_data': 'Sincronizando datos',
      'sync_completed': 'Sincronización completa',
      'data_updated_server': 'Los datos se han actualizado con el servidor.',
      'operation_error': 'Error de operación',
      'error_processing_data': 'Ocurrió un error al procesar los datos.',
    },
  };

  String translate(String key, {Map<String, String>? params}) {
    String value;
    final code = locale.languageCode;

    if (key == CategorySlugs.centrifugal || key == 'centrifugal-pumps') {
      value = (code == 'pt' || code == 'es')
          ? 'BOMBAS CENTRÍFUGAS'
          : 'CENTRIFUGAL PUMPS';
    } else if (key == CategorySlugs.submerged || key == 'deep-well-pumps') {
      value = code == 'pt'
          ? 'BOMBAS SUBMERSAS'
          : code == 'es'
          ? 'BOMBAS SUMERGIBLES'
          : 'DEEP WELL PUMPS';
    } else if (key == CategorySlugs.submersible || key == 'submersible-pumps') {
      value = code == 'pt'
          ? 'BOMBAS SUBMERSÍVEIS'
          : code == 'es'
          ? 'BOMBAS SUMERGIBLES'
          : 'SUBMERSIBLE PUMPS';
    } else {
      value = _localizedValues[code]?[key] ?? key;
    }

    if (params != null) {
      params.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'pt', 'es'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    Intl.defaultLocale = locale.toString();
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
